import type { MapLevels } from "./../utils/index.js";
import { constMap } from "./../utils/index.js";
import type { Network } from "./networks.js";
import type { Chain } from "./chains.js";

// prettier-ignore
const rpcConfig = [[
  "Mainnet", [
    ["Ethereum",  "https://ethereum-rpc.publicnode.com"],
    ["Solana",    "https://api.mainnet-beta.solana.com"],
    ["Polygon",   "https://polygon-bor-rpc.publicnode.com"],
    ["Bsc",       "https://bsc-rpc.publicnode.com"],
    ["Avalanche", "https://avalanche-c-chain-rpc.publicnode.com"],
    ["Fantom",    "https://rpcapi.fantom.network"],
    ["Celo",      "https://celo-rpc.publicnode.com"],
    ["Moonbeam",  "https://moonbeam-rpc.publicnode.com"],
    ["Sui",       "https://rpc.mainnet.sui.io"],
    ["Aptos",     "https://fullnode.mainnet.aptoslabs.com/v1"],
    ["Arbitrum",  "https://arb1.arbitrum.io/rpc"],
    ["Optimism",  "https://mainnet.optimism.io"],
    ["Base",      "https://mainnet.base.org"],
    ["Osmosis",   "https://osmosis-rpc.polkachu.com"],
    ["Cosmoshub", "https://cosmos-rpc.publicnode.com:443"],
    ["Evmos",     "https://evmos-rpc.polkachu.com"],
    ["Injective", "https://sentry.tm.injective.network"],
    ["Wormchain", "https://wormchain-rpc.quickapi.com"],
    ["Sei",       "https://sei-rpc.polkachu.com/"],
    ["Algorand",  "https://mainnet-api.algonode.cloud"],
    ["Terra2",    "https://terra-rpc.polkachu.com"],
    ["Dymension", "https://dymension-rpc.polkachu.com/"],
    ["Stargaze",  "https://stargaze-rpc.polkachu.com/"],
    ["Celestia",  "https://celestia-rpc.polkachu.com/"],
    ["Neutron",   "https://neutron-rpc.polkachu.com/"],
    ["Blast",     "https://rpc.blast.io"],
    ["Provenance","https://rpc.provenance.io/"],
    ["Noble",     "https://noble-rpc.polkachu.com/"],
    ["Linea",     "https://rpc.linea.build"],
    ["Scroll",    "https://scroll-rpc.publicnode.com"],
    ["Xlayer",    "https://xlayerrpc.okx.com/"],
    ["Gnosis",    "https://gnosis-rpc.publicnode.com"],
    ["Mantle",    "https://rpc.mantle.xyz"],
    ["Klaytn",    "https://public-en.node.kaia.io"],
    ["Snaxchain", "https://mainnet.snaxchain.io"],
    ["Berachain", "https://rpc.berachain.com"],
    ["Unichain",  "https://mainnet.unichain.org"],
    ["Worldchain","https://worldchain-mainnet.g.alchemy.com/public"],
    ["Ink",       "https://rpc-qnd.inkonchain.com"],
    ["Sonic",     "https://rpc.soniclabs.com"],
    ["HyperEVM",  "https://rpc.hyperliquid.xyz/evm"],
  ]], [
  "Testnet", [
    ["Bsc",             "https://data-seed-prebsc-1-s3.binance.org:8545"],
    ["Avalanche",       "https://api.avax-test.network/ext/bc/C/rpc"],
    ["Fantom",          "https://rpc.testnet.fantom.network"],
    ["Celo",            "https://alfajores-forno.celo-testnet.org"],
    ["Solana",          "https://api.devnet.solana.com"],
    ["Moonbeam",        "https://rpc.api.moonbase.moonbeam.network"],
    ["Sui",             "https://fullnode.testnet.sui.io"],
    ["Aptos",           "https://fullnode.testnet.aptoslabs.com/v1"],
    ["Sei",             "https://sei-testnet-rpc.polkachu.com"],
    ["Injective",       "https://testnet.sentry.tm.injective.network"],
    ["Osmosis",         "https://rpc.testnet.osmosis.zone"],
    ["Cosmoshub",       "https://rpc.sentry-02.theta-testnet.polypore.xyz"],
    ["Evmos",           "https://evmos-testnet-rpc.polkachu.com"],
    ["Wormchain",       "https://gateway.testnet.xlabs.xyz/"],
    ["Sepolia",         "https://ethereum-sepolia.publicnode.com"],
    ["Algorand",        "https://testnet-api.algonode.cloud"],
    ["Terra2",          "https://terra-testnet-rpc.polkachu.com"],
    ["ArbitrumSepolia", "https://sepolia-rollup.arbitrum.io/rpc"],
    ["OptimismSepolia", "https://sepolia.optimism.io"],
    ["BaseSepolia",     "https://sepolia.base.org"],
    ["PolygonSepolia",  "https://rpc-amoy.polygon.technology/"],
    ["Mantle",          "https://rpc.testnet.mantle.xyz"],
    ["Blast",           "https://sepolia.blast.io"],
    ["Berachain",       "https://bepolia.rpc.berachain.com/"],
    ["Seievm",          "https://evm-rpc-testnet.sei-apis.com/"],
    ["Linea",           "https://rpc.sepolia.linea.build"],
    ["Xlayer",          "https://testrpc.xlayer.tech/"],
    ["Scroll",          "https://scroll-sepolia-rpc.publicnode.com"],
    ["Gnosis",          "https://rpc.chiadochain.net"],
    ["Klaytn",          "https://public-en-kairos.node.kaia.io"],
    ["Snaxchain",       "https://testnet.snaxchain.io"],
    ["Unichain",        "https://sepolia.unichain.org"],
    ["Worldchain",      "https://worldchain-sepolia.g.alchemy.com/public"],
    ["Ink",             "https://rpc-qnd-sepolia.inkonchain.com"],
    ["HyperEVM",        "https://api.hyperliquid-testnet.xyz/evm"],
    ["Monad",           "https://testnet-rpc.monad.xyz"],
    ["Noble",           "https://noble-testnet-rpc.polkachu.com/"],
    ["Mezo",            "https://rpc.test.mezo.org"],
    ["Sonic",           "https://rpc.blaze.soniclabs.com"],
  ]], [
  "Devnet", [
    ["Ethereum",  "http://eth-devnet:8545"],
    ["Bsc",       "http://eth-devnet2:8545"],
    ["Solana",    "http://solana-devnet:8899"],
  ]],
] as const satisfies MapLevels<[Network, Chain, string]>;

const rpc = constMap(rpcConfig);

/** Default RPC Addresses by network and chain */
export const rpcAddress = (network: Network, chain: Chain) => rpc.get(network, chain) ?? "";
