kind: Job
apiVersion: batch/v1
metadata:
  name: wormhole-sdk-ts-ci-tests
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: wormhole-sdk-ts-ci-tests
          image: wormhole-sdk-ts-test
          command:
            - /bin/sh
            - -c
            - "bash /app/testing/wait-run.sh && touch /app/testing/success"
          readinessProbe:
            exec:
              command:
                - test
                - -e
                - "/app/testing/success"
            initialDelaySeconds: 60
            periodSeconds: 15